"""empty message

Revision ID: 07326cd95f03
Revises: 76e979ad8a3e
Create Date: 2023-09-08 04:14:25.573657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07326cd95f03'
down_revision = '76e979ad8a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('eye_color', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
