"""empty message

Revision ID: b8fc1769a08b
Revises: 07326cd95f03
Create Date: 2023-09-08 04:32:28.995070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fc1769a08b'
down_revision = '07326cd95f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('birth_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['eye_color'])
        batch_op.create_unique_constraint(None, ['birth_year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('eye_color',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
